### ISSUE TITLE
Documentation changes wishlist

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#33]
This issue contains a list of the changes I want to make to the documentation:

- [ ] Add an installation guide for Windows - #18
- [ ] Add dependencies installation instructions on the installation chapter
- [ ] Rename the tutorial to quickstart
- [ ] Add a proper tutorial
- [ ] Add a narrative chapter about sending messages
- [ ] Add a narrative chapter about commands
- [ ] Add a narrative chapter about localization

This list may grow.
