### ISSUE TITLE
Language overhaul

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#46]
Currently botogram support internationalization for its default messages, but that feature is available for a few languages only (Italian and English), it's undocumented, and it's really limited (no way to override messages without modifying the `.po` files, rebuilding the package and reinstalling it).

This issue tracks the progress to improve this situation.
- [x] Add narrative documentation about languages
- [x] Add some documentation about adding support for  new languages
- [x] Add a way to override language values without recompiling the `.po` files (issue #47)
