### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#48]
Before the release of botogram 1.0, there are some deprecated features which needs to be removed:

- [ ] `botogram.decorators.pass_bot`
- [ ] `botogram.decorators.pass_shared`
- [ ] `botogram.components.Component.add_shared_memory_initializer` (issue #24)
- [ ] `botogram.frozenbot.FrozenBot.init_shared_memory` (issue #24)
- [ ] `botogram.bot.Bot.init_shared_memory` (issue #24)

**Comment by thesharp** [comment]
``botogram.Message.from_`` (issue #44) should also be removed.

**Comment by pietroalbini** [comment]
Yeah, forgot to add that.
