### ISSUE TITLE
Changes applied in the Bots API 2.0 and 2.1

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#61]
The Bots API 2.0 update of the Telegram API added a bunch of things! Other than keyboard and inline queries stuff which botogram can't use yet, tons of new features were added. This issue tracks the progress to completly support the update.

* [x] ~~Add `Message.pinned_message` (no issue)~~
* [x] ~~Add `ParsedTextEntity.user` and the entity type "text_mention" (no issue)~~
* [x] ~~Add ability to edit messages (issue #55)~~
* [x] ~~Add ability to manage groups (issue #56)~~
* [x] ~~Add ability to send contacts (issue #57)~~
* [x] ~~Add support for venues (issue #58)~~
* [x] ~~Add support for message entities (issue #59)~~
* [x] ~~Rename chat membership fields of the Message objects (issue #60)~~
* [x] ~~Add ability to process edited messages (issue #63)~~
* [x] ~~Add ability to get information about chat members (issue #64)~~
* [x] ~~Add ability to get details of a specific chat (issue #65)~~
